name: Develop jobs
on:
    push:
        branches: [develop]
    pull_request:
        branches: [develop]
jobs:
    end-to-end:
        runs-on: ubuntu-latest
        container: vectorim/element-web-ci-e2etests-env:latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: End-to-End tests
              run: ./scripts/ci/end-to-end-tests.sh
            - name: Archive logs
              uses: actions/upload-artifact@v2
              with:
                path: |
                    test/end-to-end-tests/logs/**/*
                    test/end-to-end-tests/synapse/installations/consent/homeserver.log
                retention-days: 14
            - name: Download previous benchmark data
              uses: actions/cache@v1
              with:
                path: ./cache
                key: ${{ runner.os }}-benchmark
            - name: Store benchmark result
              uses: matrix-org/github-action-benchmark@jsperfentry-1
              with:
                tool: 'jsperformanceentry'
                output-file-path: test/end-to-end-tests/performance-entries.json
                fail-on-alert: false
                # Personal access token to deploy GitHub Pages branch
                github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
                # Push and deploy GitHub pages branch automatically
                auto-push: true
                # auto-push: ${{ github.ref == 'refs/heads/develop' }}
